# Generated by Django 3.1.3 on 2020-11-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(editable=False, max_length=15)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(max_length=50)),
                ('locker', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1, max_length=1, unique=True)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
